# Generated by Django 5.2.13 on 2026-06-23 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('biography', models.TextField(blank=True, verbose_name='Biographie')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Auteur',
                'verbose_name_plural': 'Auteurs',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifiée le')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('publication_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Année de publication')),
                ('publisher', models.CharField(blank=True, max_length=150, verbose_name='Éditeur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('authors', models.ManyToManyField(related_name='books', to='catalog.author', verbose_name='Auteurs')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='catalog.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Livre',
                'verbose_name_plural': 'Livres',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_code', models.CharField(max_length=50, unique=True, verbose_name='Code d’inventaire')),
                ('status', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EMPRUNTE', 'Emprunté'), ('PERDU', 'Perdu'), ('DETERIORE', 'Détérioré')], default='DISPONIBLE', max_length=20, verbose_name='Statut')),
                ('condition', models.CharField(choices=[('NEUF', 'Neuf'), ('BON', 'Bon état'), ('MOYEN', 'État moyen'), ('MAUVAIS', 'Mauvais état')], default='BON', max_length=20, verbose_name='État physique')),
                ('acquisition_date', models.DateField(blank=True, null=True, verbose_name='Date d’acquisition')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='catalog.book', verbose_name='Livre')),
            ],
            options={
                'verbose_name': 'Exemplaire',
                'verbose_name_plural': 'Exemplaires',
                'ordering': ['inventory_code'],
            },
        ),
    ]
