# Generated by Django 5.2.13 on 2026-06-23 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_at', models.DateTimeField(auto_now_add=True, verbose_name='Date d’emprunt')),
                ('due_at', models.DateTimeField(verbose_name='Date limite de retour')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de retour')),
                ('status', models.CharField(choices=[('EN_COURS', 'En cours'), ('RETOURNE', 'Retourné'), ('EN_RETARD', 'En retard'), ('PERDU', 'Perdu')], default='EN_COURS', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('book_copy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='catalog.bookcopy', verbose_name='Exemplaire')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_loans', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to=settings.AUTH_USER_MODEL, verbose_name='Élève')),
            ],
            options={
                'verbose_name': 'Emprunt',
                'verbose_name_plural': 'Emprunts',
                'ordering': ['-borrowed_at'],
            },
        ),
    ]
